### ISSUE TITLE
Caroussel met afbeeldingen verticaal op detailpagina

### ISSUE THREAD

**Issue by emacgillavry** [hetutrechtsarchief/Utrecht-Skyline#13]
Caroussel met afbeeldingen HUA wordt verticaal getoond op de detailpagina, naast de WIkipedia informatie.

**Comment by NieneB** [comment]
- [ ] Check carrousel can be made vertical

- [ ] if not place images vertically.

**Comment by NieneB** [comment]
I don't think the carousel component is made for vertical scrolling.. Needs a lot of custom adjustment.

**Comment by emacgillavry** [comment]
Besproken 24/08: lightbox is zeer krachtig. Geen caroussel meer nodig op detailpagina. Daar ligt de nadruk op de wiki-content
