### ISSUE TITLE
Bug: non matching building names (probably due to special characters in text) 

### ISSUE THREAD

**Issue by NieneB** [hetutrechtsarchief/Utrecht-Skyline#20]

**Comment by emacgillavry** [comment]
Heb je voorbeeld waar het fout gaat?

**Comment by NieneB** [comment]
Nicolaïkerk in geojson Map
Nicolaikerk in panorama json

**Comment by NieneB** [comment]
- [ ] Frederieke match correct names to json files

- [ ] Niene draws point on map from json files istead of geojson file. so one truth is used

**Comment by NieneB** [comment]
in branch issue#21ToggleDatasets
