### ISSUE TITLE
multitouch screen events

### ISSUE THREAD

**Issue by companje** [hetutrechtsarchief/Utrecht-Skyline#37]
- [ ] inzoomen met 2 vingers op het 'panorama'

**Comment by emacgillavry** [comment]
Kan je deze testen? 

https://gist.githack.com/johnd0e/c7b44648c5b365cd9b2a9662a23180e0/raw/test-fix-pointer.html

**Comment by emacgillavry** [comment]
Vanmiddag even testen op het grote scherm!

**Comment by emacgillavry** [comment]
Did not work on Windows NT 10.0; Win64; x64. Chrome 83.0.4103.116, but commit 3d39bcbe115b0309209f64627293503eac560c14 explicitly sets touchZoom.
