### ISSUE TITLE
Disable rechter muis browser menu 

### ISSUE THREAD

**Issue by emacgillavry** [hetutrechtsarchief/Utrecht-Skyline#47]
Op het grote scherm moet het browser menu met de rechter muisknop niet kunnen worden geactiveerd.

**Comment by emacgillavry** [comment]
Zie instructies in de [README](https://github.com/hetutrechtsarchief/Utrecht-Skyline/blob/master/README.md).

**Comment by companje** [comment]
## Context menu blocker

1. Plaats de map `contextmenublocker` op de desktop
2. Ga in Chrome naar `chrome://extensions/`
3. Vink de optie `Developer Mode` aan
4. Klik `Load unpacked`
5. Selecteer de map `contextmenublocker` op de desktop

Nu kunnen bezoekers niet meer het context-menu activeren.
