### ISSUE TITLE
Geselecteerde stip op kaart  highlighten na klik

### ISSUE THREAD

**Issue by emacgillavry** [hetutrechtsarchief/Utrecht-Skyline#7]
Als de gebruiker een stip op de kaart heeft geselecteerd blijft deze groen totdat een andere stip in de kaart of een andere rechthoek in het panorama is gekozen of totdat de gebruiker terugkeert naar de voorpagina.

**Comment by NieneB** [comment]
Works on clikc panorama and map. Not on returning and first time rendering
