### ISSUE TITLE
Toggle koppelen aan de kaart

### ISSUE THREAD

**Issue by emacgillavry** [hetutrechtsarchief/Utrecht-Skyline#8]
Als de gebruiker naar het jaar 1684 schakelt wordt de kaart van Specht gebruikt.

XYZ:
http://maps.georeferencer.com/georeferences/87079bbe-1741-5a83-96ce-ff86d0426d69/2019-09-30T09:58:16.234097Z/map/{z}/{x}/{y}.png?key=mpUE8UJCeHr5LXgVR1cW

TileJSON:
http://maps.georeferencer.com/georeferences/87079bbe-1741-5a83-96ce-ff86d0426d69/2019-09-30T09:58:16.234097Z/map.json?key=mpUE8UJCeHr5LXgVR1cW

Als de gebruiker naar het jaar 1669 schakelt wordt de **huidige**  kaart van Blaeu gebruikt.

XYZ:
http://maps.georeferencer.com/georeferences/e004cbea-e4f7-5b19-bf6d-54035c9a2b14/2018-04-05T14:45:19.127121Z/map/{z}/{x}/{y}.png?key=mpUE8UJCeHr5LXgVR1cW

TileJSON:
http://maps.georeferencer.com/georeferences/e004cbea-e4f7-5b19-bf6d-54035c9a2b14/2018-04-05T14:45:19.127121Z/map.json?key=mpUE8UJCeHr5LXgVR1cW

**Comment by NieneB** [comment]
- [ ] Make map layout as store variable

- [ ] change map style on switch 

- [ ] Change geojson data on switch

- [ ] empty chosen building on switch?

**Comment by NieneB** [comment]
Cross Origin Request Blocked on **Specht**
http://maps.georeferencer.com/georeferences/87079bbe-1741-5a83-96ce-ff86d0426d69/2019-09-30T09:58:16.234097Z/map.json?key=mpUE8UJCeHr5LXgVR1cW

**Comment by emacgillavry** [comment]
TileJSON kopiëren en in de app zelf hosten?

Op di 18 aug. 2020 15:56 schreef Niene <notifications@github.com>:

**Comment by NieneB** [comment]
- [ ] use tiles instead of tilejson

**Comment by NieneB** [comment]
Tile urls are not working. 
@emacgillavry  check branch **issue#8MapStyle**  file   `src/assets/mapStyleSpecht_1684.json`
_**Review urls!**_

**Comment by NieneB** [comment]
Tiles working. Tilejson info copied to style files. 
(sorry for the mix up.. )
